[DRAFT PR - DO NOT MERGE] Features add, bugs fixes & ajout d'EcoleDirecte partie 4
PapillonApp/papillon-v5 pull request #120
Opened 2023-05-17 21:04 UTC by LeGeek01

CETTE PULL REQUEST N'EST PAS COMPLÈTE !
La description sera modifiée dès que la pr sera prête à être merge

2023-05-17 21:05 UTC, LeGeek01 commented
@ecnivtwelve peux-tu resolve les conflits en supprimant ton nouveau packet du package lock stp ? j'ai fait une série de màj et j'ai trop la flemme de tout me retaper
je le rajouterai après

2023-05-17 23:41 UTC, locness3 commented on README.md
> +npm run build
bah pourquoi?

2023-05-17 23:41 UTC, locness3 commented on src/functions/fetch/GetGrades.js
> +	console.log(currentPeriod)
enlève le console.log

2023-05-17 23:41 UTC, locness3 commented on src/functions/fetch/GetGrades.js
> +		let actualPeriod1 = grades.periodes.filter(p => p.idPeriode === actualPeriod.id)
peut-être plutôt un nom genre `actualPeriodGrades`

2023-05-17 23:41 UTC, locness3 commented on src/functions/utils/displayToast.js
> +		duration: 5000,
t'es sûr de vouloir changer ces durées?

2023-05-17 23:41 UTC, moeenio commented on src/views/homepage/HomepageSetup.vue
> +    //let inner = true;
sois t'enlèves soit tu laisses là si tu sais pas ce que ça fait

2023-05-17 23:41 UTC, locness3 commented on src/views/schoollife/SchoollifeAbsItemView.vue
> +            evenement1: {
evenement sans le 1 stp

2023-05-17 23:41 UTC, locness3 commented on src/views/settings/AdvancedView.vue
> +				if(!value && !cancelled) {
bien vu merci!

2023-05-17 23:41 UTC, locness3 commented on src/views/settings/UserView.vue
> +                        displayToast.presentToastSmall("Nom modifié", "success", checkmarkOutline)
tu pourras justifier les styles de toast différents?

2023-05-18 06:56 UTC, LeGeek01 commented on README.md
> +npm run build
Tour simplement parce que ionic a un putain de bug de connectivité qui bouffe la moitié du proco en permanence

2023-05-18 06:58 UTC, LeGeek01 commented on src/functions/utils/displayToast.js
> +		duration: 5000,
Va lire des toasts pendant 2 secondes

2023-05-18 06:59 UTC, LeGeek01 commented on src/functions/fetch/GetGrades.js
> +		let actualPeriod1 = grades.periodes.filter(p => p.idPeriode === actualPeriod.id)
On s'en fiche eu nom franchement, tant que ça marche
J'en ai chié pour fix ce bug, j'ai trop la flemme de changer encore des variables

2023-05-18 07:00 UTC, LeGeek01 commented on src/views/homepage/HomepageSetup.vue
> +    //let inner = true;
D'après vue cnesh une variable pas utilisé, je l'annote dans le cas où elle pourrait servir plus tard

2023-05-18 07:00 UTC, LeGeek01 commented on src/functions/fetch/GetGrades.js
> +	console.log(currentPeriod)
Oui c'est un oubli de ma pars

2023-05-18 07:02 UTC, LeGeek01 commented on src/views/settings/UserView.vue
> +                        displayToast.presentToastSmall("Nom modifié", "success", checkmarkOutline)
C'est à dire ?

2023-05-18 07:04 UTC, LeGeek01 commented
Il a fumé locness ou ???
C'est censé être une draft pull request, de son nom elle veut dire brouillon donc pas terminée

2023-05-18 10:12 UTC, LeGeek01 commented
merde ducoup ça a revert tous les changements qui ont été fait après le conflit

2023-05-18 14:22 UTC, locness3 commented on src/functions/fetch/GetGrades.js
> +		let actualPeriod1 = grades.periodes.filter(p => p.idPeriode === actualPeriod.id)
>On s'en fiche du nom franchement, tant que ça marche
Non. Y'a d'autres développeurs qui passent après toi.

2023-05-18 14:23 UTC, locness3 commented on src/views/homepage/HomepageSetup.vue
> +    //let inner = true;
retire là du coup

2023-05-18 14:30 UTC, LeGeek01 commented on src/functions/fetch/GetGrades.js
> +		let actualPeriod1 = grades.periodes.filter(p => p.idPeriode === actualPeriod.id)
comme je te le dis, si ça ne te plaît pas tu changera après que j'ai finalisé cette pr

2023-05-19 08:41 UTC, locness3 commented on src/functions/utils/displayToast.js
> +		duration: 5000,
Ouais bv

2023-05-19 08:43 UTC, locness3 commented
La prochaine fois tu pourras essayer de séparer ça en plusieurs commits/pr? Avec git ou une interface décente tu peux choisir de n'inclure que certaines lignes de code dans un commit.

2023-05-19 08:45 UTC, locness3 commented on src/functions/fetch/GetGrades.js
> +		let actualPeriod1 = grades.periodes.filter(p => p.idPeriode === actualPeriod.id)
jprefere ne pas accepter du code moche que de devoir repasser après car j'ai la flemme mdrr

2023-05-19 08:47 UTC, locness3 commented on README.md
> +npm run build
tant qu'on perd pas de fonctionnalité ça me va

2023-05-19 08:52 UTC, locness3 commented on src/views/settings/UserView.vue
> +                        displayToast.presentToastSmall("Nom modifié", "success", checkmarkOutline)
Pourquoi utiliser des grands et petits styles de toast par rapport au toast natif qon avait avant?

2023-05-19 09:12 UTC, LeGeek01 commented on src/functions/fetch/GetGrades.js
> +		let actualPeriod1 = grades.periodes.filter(p => p.idPeriode === actualPeriod.id)
ça tombe bien c'est pas toi qui accepte mdr

2023-05-19 09:13 UTC, LeGeek01 commented
intérêt ?

2023-05-19 09:30 UTC, locness3 commented on src/functions/fetch/GetGrades.js
> +		let actualPeriod1 = grades.periodes.filter(p => p.idPeriode === actualPeriod.id)
vrai

2023-05-19 09:45 UTC, LeGeek01 commented on src/views/settings/UserView.vue
> +                        displayToast.presentToastSmall("Nom modifié", "success", checkmarkOutline)
bah cite moi les différents style, parce que je vois pas de style grand et de style petit

2023-05-20 09:19 UTC, locness3 commented
[Git Best Practices, sur freecodecamp.org](https://www.freecodecamp.org/news/git-best-practices-commits-and-code-reviews/) 
> Smaller commits make it easier to revert code to a previous state if there's a problem. If your commit affects too many areas, reverting back could mean losing a lot of code.
> It's also far easier for reviewers to understand what the code is doing if it's related to one purpose.
> ...
> Why is [un gros commit] so bad?
> 1. Firstly there's too much happening within this commit. Too many files mean that if we need to revert the validation changes, only we can't. We'd have to revert the whole commit losing the products and registration changes.

de mon pdv, ça permet aussi de prendre plus facilement des changements individuels pour une release ou un fork

2023-05-27 13:13 UTC, locness3 commented
Je te vois commenter dans divers tickets que tu ajouteras quelque chose dans "ta pull request" j'imagine qu'il s'agit de celle là? Pourrais-tu implémenter ce qui n'a pas de rapport avec EcoleDirecte et n'est pas déja ici dans des PR distinctes afin de faciliter l'intégration de ces changements individuels?

2023-05-27 13:43 UTC, LeGeek01 commented
pourquoi ça faciliterai l'intégration ? une fois la pr merge tout sera mis dans la branch dev

2023-05-27 17:04 UTC, locness3 commented
parce qu'on peut y aller un par un, ça peut être plus rapide et moins de risqie d'erreur

2023-05-27 17:06 UTC, locness3 commented on capacitor.config.ts
> +		"CapacitorHttp": {
Alors c'est bien mais moi y'a plein de trucs qui marchaient pas quand je l'ai fait. Tu peux lire #114 stp?

2023-05-27 17:07 UTC, locness3 commented on capacitor.config.ts
> +		"CapacitorHttp": {
Ça pose zéro problème en web, mais sur mobile si.

2023-05-28 08:38 UTC, lucas-luchack requested changes

2023-05-28 08:38 UTC, lucas-luchack commented on capacitor.config.ts
> +		url: "http://localhost:8100/" // Address of the server running locally
Retire ça sinon l'application ne marchera plus lors du build

2023-05-28 08:38 UTC, lucas-luchack commented on src/views/schoollife/SchoollifeAbsItemView.vue
> +            evenement1: {
@LeGeek01 si le 1 n'est pas indispensable, retire-le ;)

2023-05-28 08:38 UTC, lucas-luchack commented on src/views/timetable/TimetableView.vue
> +  //import { Share } from '@capacitor/share';
Retire le carrément, la fonction de partage est dans l'autre fichier maintenant

2023-05-28 09:02 UTC, locness3 commented on src/views/timetable/TimetableView.vue
> +  //import { Share } from '@capacitor/share';
Je lui avais fait le même commentaire, jsp où est passé ma review, de "soit tu laisses soit tu retires" dans ce genre de cas

2023-05-28 09:03 UTC, locness3 commented on capacitor.config.ts
> +		url: "http://localhost:8100/" // Address of the server running locally
Voir commentaire ci-dessus et #114

2023-05-28 09:11 UTC, LeGeek01 commented
faudra songer à trouver une alternative à @hugotomazi/capacitor-navigation-bar@2.0.1, qui ne supporte pas capacitor 5 et qui génère une erreur dans npm et empêche le build de se faire

2023-05-31 13:28 UTC, moeenio commented
bon, faudra pas être choqué si jamais la pr n'est pas acceptée à la fin

2023-06-11 12:22 UTC, merged

2023-06-11 21:25 UTC, lucas-luchack commented
> bon, faudra pas être choqué si jamais la pr n'est pas acceptée à la fin.

Comme il l'a dit, la prochaine fois, on ne prendra même pas le temps de regarder, ça sera refusé directement...

2023-06-12 06:39 UTC, locness3 commented
Là vous avez fait totalement l'inverse lol