[NEW] Corrélation add item homework/timetable
PapillonApp/papillon-v5 pull request #147
Opened 2023-06-11 15:07 UTC by sivelswhy

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [X] You can **build successfully** the whole project with your changes locally
- [X] You use the coding conventions and the **naming conventions** of the project
- [X] You use **tabs** for indentation
- [X] You make sure that your PR is **not a duplicate**
- [X] This PR is **ready** to be reviewed and merged
- [X] This PR merges into the **`development`** branch or in the specific branch of the feature you want to merge into
- [X] There is no **`TODO`** in the code
- [X] There is no spelling or grammatical errors in the code
- [X] Details of the issue or feature are documented below
- [X] This PR is **not** a **breaking change** (e.g. changes that would cause existing functionality to change)

## Explain Changes
Lorsque l'on veux ajouter un timetable/homework manuellement il y a deux manières :
- Dans la timetable, il y a un bouton `+` en bas à droite de l'écran
- Dans les homeworks, il y a un texte `Ajouter un devoir manuellement`
Ainsi, je trouve illogique que d'un côté ce sois un texte et de l'autre ce sois une icone.
Ce que j'ai donc fait, c'est que j'ai enlevé le texte dans homeworks, et j'ai plutôt fait comme dans la timetable

|       | Homework | Timetable |
|:-------:|:----------:|:-----------:|
| Avant |![image](https://github.com/PapillonApp/Papillon/assets/82051273/a8583347-24e2-4268-89bf-d0a7aad83c21)|![image](https://github.com/PapillonApp/Papillon/assets/82051273/5b3b6d07-f77a-41cb-80c9-2c67f476d529)|
| Après |![image](https://github.com/PapillonApp/Papillon/assets/82051273/a956a9fa-0e31-480b-9a4e-9bead9b9344b)|![image](https://github.com/PapillonApp/Papillon/assets/82051273/9262a602-9ff8-4c35-b8cc-3af3ebf429bf)|

## Proposed changelog

| Français `fr` |
| --- |
| Corrélation add item homework/timetable |

### Note
Before merging this PR, you will need the approval of at least one of the following people:
- @ecnivtwelve
- @lucas-luchack

So be patient ;)

### Informations supplémentaires

2023-06-11 21:19 UTC, lucas-luchack requested changes
Le bouton pour l'ajout dans les `homeworks` n'est pas correctement implémenté. (difforme)
Voir avec @ecnivtwelve si ce design lui convient...

2023-06-12 18:03 UTC, Ahhj93 requested changes

2023-06-12 18:03 UTC, Ahhj93 commented on src/views/homework/HomeworkView.vue
> +			</IonFab>
```suggestion
            <IonFab slot="fixed" vertical="bottom" horizontal="end" class="newHomeworksBtnFab">
				<ion-button @click="addHomework($event)" size="large" shape="round" class="newHomeworksBtn" mode="md" aria-label="Ajouter un devoir">
					<span class="material-symbols-outlined mdls" slot="icon-only">add</span>
				</ion-button>
			</IonFab>
```

2023-06-12 18:17 UTC, sivelswhy commented
> Le bouton pour l'ajout dans les `homeworks` n'est pas correctement implémenté. (difforme)
> Voir avec @ecnivtwelve si ce design lui convient...

Effectivement, j'avais remarqué cela, mais je ne trouve pas de fix à cela

2023-06-12 18:43 UTC, Ahhj93 commented
@sivelswhy J'ai réussi à fix le problème, je t'ai fait une PR sur t'a branche https://github.com/sivelswhy/Papillon/pull/3

2023-06-12 19:15 UTC, sivelswhy commented
Fix boutton par @Ahhj93 ⬆️

2023-06-12 19:25 UTC, ecnivtwelve approved these changes
Implémentation OK ✅

2023-06-12 19:27 UTC, merged