README en Français
PapillonApp/papillon-v5 pull request #156
Opened 2023-06-14 13:12 UTC by sivelswhy

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [X] You can **build successfully** the whole project with your changes locally
- [X] You use the coding conventions and the **naming conventions** of the project
- [X] You use **tabs** for indentation
- [X] You make sure that your PR is **not a duplicate**
- [X] This PR is **ready** to be reviewed and merged
- [X] This PR merges into the **`development`** branch or in the specific branch of the feature you want to merge into
- [X] There is no **`TODO`** in the code
- [X] There is no spelling or grammatical errors in the code
- [X] Details of the issue or feature are documented below
- [X] This PR is **not** a **breaking change** (e.g. changes that would cause existing functionality to change)

## Explain changes
Changement du README principal en français, ajout d'un lien vers en autre readme, lui en anglais, plus corrections de quelques fautes

## Proposed changelog

| Français `fr` |
| --- |
| README en Français |

### Note
Before merging this PR, you will need the approval of at least one of the following people:
- @ecnivtwelve
- @lucas-luchack

So be patient ;)

### Informations supplémentaires

2023-06-14 17:02 UTC, locness3 commented
Je te conseillerais de le nommer README.en.md

2023-06-14 17:25 UTC, sivelswhy commented
> Je te conseillerais de le nommer README.en.md

je trouve qu'en _EN c'est plus logique

2023-06-14 19:05 UTC, ecnivtwelve requested changes
"Documentation in English" n'est pas très bien placé + la doc et le readme ce n'est pas la même chose

2023-06-14 19:12 UTC, sivelswhy commented
J'ai changé tout ça, le texte, et le placement en espérant que ça te convienne

2023-06-14 23:10 UTC, LeGeek01 commented
Ça me semble ok

2023-06-14 23:10 UTC, LeGeek01 approved these changes

2023-06-14 23:10 UTC, LeGeek01 commented on README.md
> +## Construit avec
j'aurais plus mis "développé avec" que construit, à voir ce que t'en penses

2023-06-14 23:10 UTC, LeGeek01 commented on README.md
> +Pour mettre en place une copie locale et la faire fonctionner, suivez ces étapes simples.
"Pour avoir une copie locale" et pas "mettre en place"

2023-06-14 23:10 UTC, LeGeek01 commented on README.md
> +* Si vous avez des suggestions pour ajouter ou supprimer des projets, n'hésitez pas à [ouvrir un problème](https://github.com/PapillonApp/Papillon/issues/new) pour en discuter, ou créez directement u
à ouvrir **une issue** ; je pense qu'il serait plus judicieux de garder le mot anglais, l'onglet étant lui-même en anglais (et pour ceux qui ne sont pas familiers avec l'anglais)

2023-06-14 23:10 UTC, LeGeek01 commented on README.md
> +Distribué sous licence GPL-3.0. Allez voir [LICENSE](https://github.com/PapillonApp/Papillon/blob/development/LICENSE) pour plus d'information
"Allez voir" --> "Rendez-vous sur", ça fais plus français je trouve

2023-06-14 23:10 UTC, LeGeek01 commented on README.md
> +* **Astrow** - *Étudiante français au lycée* - [Astrow](https://github.com/Astrow25) - *Développeur et testeur*
tu diras à google traduction que ces gens la ne sont pas des meufs ptdrrrrr

2023-06-14 23:11 UTC, LeGeek01 commented
Et merde évidement j'ai approuvé le mauvais commit

2023-06-15 08:42 UTC, sivelswhy commented on README.md
> +* **Astrow** - *Étudiante français au lycée* - [Astrow](https://github.com/Astrow25) - *Développeur et testeur*
c'était deepl, j'avais la flemme mdr, je passais juste derrière pour vérifier

2023-06-16 00:43 UTC, locness3 commented on README.md
> +## Construit avec
built c'est construit littéralement et c'est plus large que "développé"

2023-06-16 00:44 UTC, locness3 commented on README.md
> +Distribué sous licence GPL-3.0. Allez voir [LICENSE](https://github.com/PapillonApp/Papillon/blob/development/LICENSE) pour plus d'information
ça devrait être "consultez"

2023-06-18 10:15 UTC, sivelswhy reviewed
Les gars c'est carré comme PR

2023-06-21 07:38 UTC, merged