Ajouter un lien pour les donations dans les paramètres
PapillonApp/papillon-v5 pull request #52
Opened 2023-03-11 09:54 UTC by sivelswhy

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] You can **build successfully** the whole project with your changes locally
- [ ] You use the coding conventions and the **naming conventions** of the project
- [ ] You use **tabs** for indentation
- [X] You make sure that your PR is **not a duplicate**
- [X] This PR is **ready** to be reviewed and merged
- [X] This PR merges into the **`development`** branch
- [X] There is no **`TODO`** in the code
- [X] There is no spelling or grammatical errors in the code
- [X] Details of the issue or feature are documented below
- [X] This PR is **not** a **breaking change** (e.g. changes that would cause existing functionality to change)

## Proposed changelog

| Français `fr` |
| --- |
| La pullrequest que j'effectue à présent rajoute un bouton qui redirige vers la page ko-fi (similaire à ceux dans l'image ci-dessous). L'icone utilisé est [celle-ci](https://fonts.google.com/icons?icon.query=donation&selected=Material+Symbols+Outlined%3Avolunteer_activism%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048), trouvé sur google fonts, comme le reste des icones que vous avez utilisé |
![IMG_3248](https://user-images.githubusercontent.com/82051273/224477609-47a85b22-4291-47c4-907b-474bab1f1630.jpeg).
Je suis désolé si cette pullrequest contient des erreurs, je n'ai jamais développé en vue ni ion ou jsp quoi
### Note
Before merging this PR, you will need the approval of at least one of the following people:
- @ecnivtwelve
- @lucas-luchack

So be patient ;)

### Informations supplémentaires

2023-03-11 10:29 UTC, lucas-luchack commented
Super merci, est ce que tu peux cependant modifier le texte vers quelle que chose de plus cordial car "effectuer une donation" et un peu trop formel je pense 😉

2023-03-11 10:32 UTC, lucas-luchack requested changes

2023-03-11 10:32 UTC, lucas-luchack commented on src/views/settings/SettingsView.vue
> +                    <h2>Effectuer une donation</h2>
Super merci, est ce que tu peux cependant modifier le texte vers quelle que chose de plus cordial car "effectuer une donation" et un peu trop formel je pense 😉

2023-03-11 11:16 UTC, sivelswhy commented on src/views/settings/SettingsView.vue
> +                    <h2>Effectuer une donation</h2>
J'ai mis "Nous soutenir", en espérant que ça te plaise x)

2023-03-11 11:20 UTC, sivelswhy commented on src/views/settings/SettingsView.vue
> +                <span class="material-symbols-outlined mdls" slot="start">volunteer_activism</span>
![image](https://user-images.githubusercontent.com/82051273/224481358-1141f8a9-9f7b-4727-84de-3deecfde07bf.png)

2023-03-11 13:07 UTC, lucas-luchack approved these changes

2023-03-11 13:10 UTC, merged

2023-03-13 15:30 UTC, moeenio commented
> je ne peux donc pas tester la fonction.

Tu peux tester dans ton navigateur, c'est marqué dans le readme je crois.