Adding icons & changing text
PapillonApp/papillon-v5 pull request #53
Opened 2023-03-11 16:39 UTC by CuauhFrMx

## Pull request checklist

My PR fulfills the requirements:
- [x] You can **build successfully** the whole project with your changes locally
- [x] You use the coding conventions and the **naming conventions** of the project
- [x] You use **tabs** for indentation
- [x] You make sure that your PR is **not a duplicate**
- [x] This PR is **ready** to be reviewed and merged
- [x] This PR merges into the **`development`** branch
- [x] There is no **`TODO`** in the code
- [x] There is no spelling or grammatical errors in the code
- [x] Details of the issue or feature are documented below
- [x] This PR is **not** a **breaking change** (e.g. changes that would cause existing functionality to change)

## Proposed changelog

| Français `fr` | Anglais `en`| 
| --- | --- |
| J'ai remplacé "Aie aie aie" par "Aïe aïe aïe" (c'est mieux avec accent) | Changed "aie" to "aïe"|
| J'ai changé le texte de réaction pour une nouvelle note inférieure à 5 (pour qu'il soit différent de celui pour une note entre supérieure à 5) | changed reaction for a new note under 5 |
| J'ai rajouté des icônes lors de la création d'une heure de cours, à gauche des input | added icons near to the input on the popup for creating a course|

2023-03-11 17:28 UTC, lucas-luchack requested changes
Refusée :
- Modification de permissions de fichier
- Changements incorrect

![image](https://user-images.githubusercontent.com/39491773/224502930-75af2941-b6d1-4be4-a710-3574785aecf5.png)

**Merci de vérifier vos changements avant de les soumettre**

2023-03-11 17:36 UTC, lucas-luchack commented
Étant donnée les modifications à apporter, je me permet de fermer cette PR.
Je récupère votre code et je le commit sur le répo correctement en co-authors.

2023-03-11 17:36 UTC, closed without merging

2023-03-11 17:37 UTC, CuauhFrMx commented
j'ai pas compris mais ok no problem

2023-03-11 17:41 UTC, lucas-luchack commented
Vous avez rajouté une icone là où il y en a déjà (voir screen) ce qui est plutôt étrange, et les permissions des fichiers ont été modifiés, sinon merci pour votre contribution !

2023-03-11 17:57 UTC, lucas-luchack commented
Vos contributions ont été ajoutées

2023-03-13 15:28 UTC, locness3 commented
> Vous avez rajouté une icone là où il y en a déjà (voir screen) 

mdr le screen fait la taille d'une favicon impossible de voir de quoi il s'agit