Ajout d'ED : partie 1
PapillonApp/papillon-v5 pull request #66
Opened 2023-03-20 20:20 UTC by LeGeek01

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] You can **build successfully** the whole project with your changes locally
- [x] You use the coding conventions and the **naming conventions** of the project
- [x] You use **tabs** for indentation
- [x] You make sure that your PR is **not a duplicate**
- [x] This PR is **ready** to be reviewed and merged
- [x] This PR merges into the **`development`** branch
- [ ] There is no **`TODO`** in the code
- [x] There is no spelling or grammatical errors in the code
- [x] Details of the issue or feature are documented below
- [ ] This PR is **not** a **breaking change** (e.g. changes that would cause existing functionality to change)

## Proposed changelog

| Français `fr` |
| --- |
| Ajout d'EcoleDirecte : Partie 1 |
Voici la première partie de l'ajout d'EcoleDirecte dans Papillon. Les fonctionnalités qui fonctionnent pour le moment sont : Connexion, EDT, une partie de l'Accueil.
Certaines fetch functions ont été modifiées mais ne fonctionnent pas correctement pour le moment, notamment les devoirs à faire et les notes. La vie scolaire fonctionne mais comporte des bugs d'affichage.
À noter qu'actuellement des requêtes directes sont faites à l'api, sans l'utilisation d'un module. Ceci sera changé dans la prochaine Pull Request.
Autre point à noter : les menus de l'appli sont syncronisés aux modules activés ou non selon l'établissement.

### Note
Before merging this PR, you will need the approval of at least one of the following people:
- @ecnivtwelve
- @lucas-luchack

So be patient ;)

### Informations supplémentaires

2023-03-20 21:28 UTC, ecnivtwelve commented
Le code est très clean, il faudrait juste test si l'app tourne bien en elle-même sur ÉcoleDirecte.
Quelques trucs qu'on à trouvé sur la partie Pronote (et login) avec @lucas-luchack :

- Le login ED ouvre directement le modal de connexion dans une page vide
- Il y a deux onglets paramètres qui ramènent dans la même vue
- L'onglet actualités est manquant (Pronote)
- Erreur inconnue : `Cannot read properties of undefined (reading '$el')
TypeError: Cannot read properties of undefined (reading '$el')
    at eval (webpack-internal:///./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/views/login/pronote/SchoolSelection.vue?vue&type=script&lang=js:305:25)`

2023-03-20 21:29 UTC, lucas-luchack requested changes
Avant que ce soit accepté pouvez vous corriger ceci :
![image](https://user-images.githubusercontent.com/39491773/226469931-1584d38a-f31b-4f1c-b855-37a195be258f.png)

Sinon good job

2023-03-20 21:38 UTC, LeGeek01 commented
Je n'arrive pas à reproduire l'erreur que vous avez, pourriez-vous me dire comment vous faites ?
Pour l'onglet actualité il sera rajouté prochainement, c'est pas une feature activé chez tout le monde

2023-03-20 21:39 UTC, LeGeek01 commented
Ah pardon j'avais mal compris pour l'actualité, je fixe ça demain matin

2023-03-20 21:40 UTC, LeGeek01 commented
Après visiblement l'erreur que vous citez viens de la connexion pronote, or je n'ai pas le souvenir d'avoir touché à ce script

2023-03-20 21:40 UTC, LeGeek01 commented
Après visiblement l'erreur que vous citez viens de la connexion pronote, or je n'ai pas le souvenir d'avoir touché à ce script

2023-03-20 21:44 UTC, LeGeek01 commented
Flûte j'ai redémandé une vérification sans mettre lzs commits

2023-03-20 22:03 UTC, LeGeek01 commented
et merde ça a annulé nos changements

2023-03-20 22:20 UTC, LeGeek01 commented
bon avec ça :
- Pas d'erreur à la connexion sur pronote
- L'onglet actualité sur pronote est bien présent
- Par contre, l'accueil ne marche plus, ça tourne en boucle sur "Chargement des données"

2023-03-21 16:55 UTC, LeGeek01 commented
@lucas-luchack possible de rejeter un coup d'oeil ? j'ai normalement fix tout ce qu'il fallait

2023-03-21 18:06 UTC, LeMaitre4523 commented
Bonjour, du coup l'onglet actualités de pronote à été rajouté, le deuxième bouton paramètres a été retiré et le modal à la connexion aussi, pour ce qui ai de l'erreur, je ne vois pas ce que je peux faire, c'est la même chose que pour pronote

2023-03-21 18:44 UTC, LeMaitre4523 reviewed
Normalement tout a été corrigé comme dit juste au dessus

2023-03-21 19:32 UTC, LeGeek01 commented
moi et mes missclicks...

2023-03-21 19:34 UTC, lucas-luchack approved these changes
A tester plus en profondeur par les utilisateurs

2023-03-21 19:35 UTC, LeGeek01 commented
le mieux serait de mettre en bêta ed quand la majorité des fonctionnalités seront disponibles, la pour l'instant ça ne vaut pas trop le coup

2023-03-21 19:37 UTC, merged

2023-03-21 19:46 UTC, LeGeek01 commented
d'ailleurs pourquoi l'avoir mis sur une autre branche que "développement" ?